on:
  push:
    branches:
      - ci/develop
      - ci/develop-linux-latest
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/linux-reusable.yml@develop
    with:
      aws-ami-id: ami-098154f774f68e105
      aws-sg-id: sg-0ca7912782cf1538b
      runTests: false
      package-name: febio-studio
      requires-sdk: true
      sdk-config: |
        {
          "sdk_path": "ci/develop",
          "version": "v4.5",
        }
    secrets: inherit
