on:
  push:
    branches: [ ci/reusable-workflow-windows ]
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/windows-reusable.yml@reusable-worfklow-windows
    with:
      aws-ami-id: ami-03ec355dfb8dfb48a
      aws-sg-id: sg-0ca7912782cf1538b
      aws-instance-type: c5a.8xlarge
      runTests: false
      package-name: febio-studio
      requires-sdk: true
      sdk-config: |
        {
          "sdk_path": "ci/reusable-workflow-windows",
          "version": "v4.3",
        }
    secrets: inherit
