on:
  push:
    branches: [ ci/* ]
  workflow_dispatch:
    inputs:
      runTests:
        description: "Run tests?"
        required: false
        type: boolean
        default: false
jobs:
  call_workflow:
    uses: febiosoftware/febio-workflows/.github/workflows/windows-reusable.yml@develop
    with:
      aws-ami-id: ami-034c4b6918ffa15c1
      aws-sg-id: sg-0ca7912782cf1538b
      aws-instance-type: c4.4xlarge
      runTests: false
      package-name: febio-studio
      requires-sdk: true
      sdk-config: |
        {
          "sdk_path": "windows-infrastructure",
          "version": "v4.3",
        }
    secrets: inherit
